/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Thai;

import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ACER
 */
public class GUI extends javax.swing.JFrame {
    DefaultTableModel dtm;
    Date nt = new Date();
    QLNhanVien a = new QLNhanVien();

    /**
     * Creates new form GUI
     */
    public GUI() {
        initComponents();
        setLocationRelativeTo(null);
        dtm = (DefaultTableModel) tblHienThi.getModel();
        dtm.setColumnIdentifiers(new Object[]{"Nhân Viên","Mã","Họ Tên","SĐT","Email","Ngày Sinh","Giới tính","Lương Cơ Bản","Số Giờ Overtime","Phát Hiện Lỗi","Lương"});
        cxbTach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALL","Lập trình viên", "Kiểm chứng viên" }));
        cxbSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sắp Xếp Lương Tăng", "Sắp Xếp Lương Giảm" }));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblMa = new javax.swing.JLabel();
        lblHoTen = new javax.swing.JLabel();
        lblSDT = new javax.swing.JLabel();
        lblMail = new javax.swing.JLabel();
        lblNgaySinh = new javax.swing.JLabel();
        lblGT = new javax.swing.JLabel();
        lblMail3 = new javax.swing.JLabel();
        rbtLapTrinhVien = new javax.swing.JRadioButton();
        rbtKiemChungVien = new javax.swing.JRadioButton();
        txtMa = new javax.swing.JTextField();
        txtHoTen = new javax.swing.JTextField();
        txtSDT = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtNgaySinh = new javax.swing.JTextField();
        rbtNam = new javax.swing.JRadioButton();
        rbtNu = new javax.swing.JRadioButton();
        txtLuongCoBan = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHienThi = new javax.swing.JTable();
        btnDocFile = new javax.swing.JButton();
        btnThem = new javax.swing.JButton();
        lblChung = new javax.swing.JLabel();
        txtChung = new javax.swing.JTextField();
        btnCapNhat = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnThongKe = new javax.swing.JButton();
        btnLuuFile = new javax.swing.JButton();
        lblHienThi = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnLuongCaoNhat = new javax.swing.JButton();
        cxbTach = new javax.swing.JComboBox<>();
        lblTach = new javax.swing.JLabel();
        btnXoaMa = new javax.swing.JButton();
        btnTimTheoMa = new javax.swing.JButton();
        cxbSapXep = new javax.swing.JComboBox<>();
        lblTach1 = new javax.swing.JLabel();
        btnThoat = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 153, 153));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 28)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Quản Lý Nhân Viên");
        jLabel1.setToolTipText("");

        lblNhanVien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNhanVien.setText("Nhân Viên");

        lblMa.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMa.setText("Mã");

        lblHoTen.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblHoTen.setText("Họ Tên");

        lblSDT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblSDT.setText("SĐT");

        lblMail.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMail.setText("Email");

        lblNgaySinh.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNgaySinh.setText("Ngày sinh");

        lblGT.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblGT.setText("Giới tính");

        lblMail3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblMail3.setText("Lương cơ bản");

        buttonGroup1.add(rbtLapTrinhVien);
        rbtLapTrinhVien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbtLapTrinhVien.setSelected(true);
        rbtLapTrinhVien.setText("Lập Trình Viên");
        rbtLapTrinhVien.setToolTipText("");
        rbtLapTrinhVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtLapTrinhVienActionPerformed(evt);
            }
        });

        buttonGroup1.add(rbtKiemChungVien);
        rbtKiemChungVien.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbtKiemChungVien.setText("Kiểm Chứng Viên");
        rbtKiemChungVien.setToolTipText("");
        rbtKiemChungVien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtKiemChungVienActionPerformed(evt);
            }
        });

        txtMa.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtHoTen.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtSDT.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtEmail.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtNgaySinh.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        buttonGroup2.add(rbtNam);
        rbtNam.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbtNam.setText("Nam");
        rbtNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtNamActionPerformed(evt);
            }
        });

        buttonGroup2.add(rbtNu);
        rbtNu.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        rbtNu.setText("Nữ");

        txtLuongCoBan.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        tblHienThi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tblHienThi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHienThiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHienThi);

        btnDocFile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnDocFile.setText("Đọc File");
        btnDocFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDocFileActionPerformed(evt);
            }
        });

        btnThem.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        lblChung.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblChung.setText("Số giờ overtime");

        txtChung.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        btnCapNhat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnCapNhat.setText("Cập nhật");
        btnCapNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCapNhatActionPerformed(evt);
            }
        });

        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoa.setText("Xóa");
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnThongKe.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThongKe.setText("Thống kê");
        btnThongKe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongKeActionPerformed(evt);
            }
        });

        btnLuuFile.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLuuFile.setText("Lưu File");
        btnLuuFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuFileActionPerformed(evt);
            }
        });

        lblHienThi.setFont(new java.awt.Font("Times New Roman", 0, 12)); // NOI18N
        lblHienThi.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHienThi.setText("......");

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/NhanVien1.png"))); // NOI18N

        btnLuongCaoNhat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnLuongCaoNhat.setText("Lương Cao Nhất");
        btnLuongCaoNhat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuongCaoNhatActionPerformed(evt);
            }
        });

        cxbTach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cxbTach.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cxbTach.setToolTipText("");
        cxbTach.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxbTachActionPerformed(evt);
            }
        });

        lblTach.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTach.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTach.setText("Phân Loại Tách");

        btnXoaMa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnXoaMa.setText("Xóa Mã");
        btnXoaMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaMaActionPerformed(evt);
            }
        });

        btnTimTheoMa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnTimTheoMa.setText("Tìm kiếm mã");
        btnTimTheoMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTimTheoMaActionPerformed(evt);
            }
        });

        cxbSapXep.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        cxbSapXep.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cxbSapXep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cxbSapXepActionPerformed(evt);
            }
        });

        lblTach1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTach1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTach1.setText("Sắp Xếp");

        btnThoat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(356, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 904, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblMa, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblSDT, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMail, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(35, 35, 35)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(txtSDT)
                                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(96, 96, 96)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(lblChung, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblGT, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblMail3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtLuongCoBan, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(rbtNam)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtNu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(txtNgaySinh, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtChung, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(145, 145, 145))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 523, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lblNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(22, 22, 22)
                                        .addComponent(rbtLapTrinhVien, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(rbtKiemChungVien, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(157, 157, 157))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnDocFile, javax.swing.GroupLayout.DEFAULT_SIZE, 115, Short.MAX_VALUE)
                                    .addComponent(btnXoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(50, 50, 50)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(btnCapNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnLuuFile, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btnThongKe))
                                .addGap(57, 57, 57)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnLuongCaoNhat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnTimTheoMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnXoaMa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(53, 53, 53)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(lblTach)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(cxbTach, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                            .addComponent(lblTach1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cxbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(93, 93, 93)
                                        .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(235, 235, 235))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblHienThi, javax.swing.GroupLayout.PREFERRED_SIZE, 617, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(374, 374, 374))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(jLabel1)
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNhanVien, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(rbtLapTrinhVien)
                            .addComponent(rbtKiemChungVien)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMa)
                            .addComponent(txtMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblHoTen)
                            .addComponent(txtHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSDT)
                            .addComponent(txtSDT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMail)
                            .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNgaySinh)
                            .addComponent(txtNgaySinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGT)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(rbtNam)
                                .addComponent(rbtNu)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblMail3)
                            .addComponent(txtLuongCoBan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtChung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblChung, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(lblHienThi)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDocFile)
                    .addComponent(cxbTach, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTach, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnThongKe)
                    .addComponent(btnXoaMa))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnXoa)
                    .addComponent(btnCapNhat)
                    .addComponent(btnTimTheoMa)
                    .addComponent(cxbSapXep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblTach1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuuFile)
                    .addComponent(btnLuongCaoNhat)
                    .addComponent(btnThem)
                    .addComponent(btnReset)
                    .addComponent(btnThoat))
                .addContainerGap(443, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDocFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDocFileActionPerformed
        // TODO add your handling code here:
        JFileChooser fc = new JFileChooser();
        fc.showOpenDialog(null);
        String tenFile = fc.getSelectedFile().getPath();
        a.docFile("NhanVien.txt");
        loadData(a.getA());
    }//GEN-LAST:event_btnDocFileActionPerformed

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        
        StringBuilder sb = new StringBuilder();
        if (txtMa.getText().equals("")) {
            txtMa.setBackground(Color.red);
            sb.append("Mã nhân viên không được để trống\n");
        } else {
            txtMa.setBackground(Color.white);
        }
        if ((txtHoTen).getText().equals("")) {
            txtHoTen.setBackground(Color.red);
            sb.append("Họ tên nhân viên không được để trống\n");
        } else {
            txtHoTen.setBackground(Color.white);
        }
        if (txtSDT.getText().equals("")) {
            txtSDT.setBackground(Color.red);
            sb.append("SĐT nhân viên không được để trống\n");
        } else {
            txtSDT.setBackground(Color.white);
        }
        if (txtNgaySinh.getText().equals("")) {
            txtNgaySinh.setBackground(Color.red);
            sb.append("Ngày sinh nhân viên không được để trống\n");
        } else {
            txtNgaySinh.setBackground(Color.white);
        }
        if (txtLuongCoBan.getText().equals("")) {
            txtLuongCoBan.setBackground(Color.red);
            sb.append("Lương cơ bản nhân viên không được để trống\n");
        } else {
            txtLuongCoBan.setBackground(Color.white);
        }
        if (rbtLapTrinhVien.isSelected()) {
            if (txtChung.getText().equals("")) {
                txtChung.setBackground(Color.red);
                sb.append("Số giờ overtime nhân viên không được để trống\n");
            } else {
                txtChung.setBackground(Color.white);
            }

        } else if (rbtKiemChungVien.isSelected()) {
            if (txtChung.getText().equals("")) {
                txtChung.setBackground(Color.red);
                sb.append("Số lỗi nhân viên không được để trống\n");
            } else {
                txtChung.setBackground(Color.white);
            }

        }

        if (sb.length() > 0) {
            JOptionPane.showMessageDialog(null, "Thông tin nhân viên không được để trống", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        String ma = txtMa.getText();
        String ten = txtHoTen.getText();
        String sdt = txtSDT.getText();
        String mail = txtEmail.getText();
        Date nt = new Date(txtNgaySinh.getText());
        boolean gioiTinh = rbtNam.isSelected();
        double luongCoBan = Double.parseDouble(txtLuongCoBan.getText());

        NhanVien x = null;

        if (rbtLapTrinhVien.isSelected()) {
            int soGioTangCa = Integer.parseInt(txtChung.getText());
            x = new LapTrinhVien(soGioTangCa, ma, ten, sdt, mail, nt, gioiTinh, luongCoBan);
        } else if (rbtKiemChungVien.isSelected()) {
            int soLoiPhatHien = Integer.parseInt(txtChung.getText());
            x = new KiemChungVien(soLoiPhatHien, ma, ten, sdt, mail, nt, gioiTinh, luongCoBan);
        }

        if (x != null && a.them(x)) {
            loadData(a.getA());
            JOptionPane.showMessageDialog(null, "Thêm thành công!");
            lblHienThi.setText("Bạn vừa thêm " + ma + " vào danh sách");
        } else {
            JOptionPane.showMessageDialog(null, "Đã có " + ma + " này trong danh mục");
        }

        ClearForm();
    }//GEN-LAST:event_btnThemActionPerformed

    private void rbtLapTrinhVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtLapTrinhVienActionPerformed
        // TODO add your handling code here:
        lblChung.setText("Số giờ overtime");
        txtChung.setVisible(true);
    }//GEN-LAST:event_rbtLapTrinhVienActionPerformed

    private void rbtKiemChungVienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtKiemChungVienActionPerformed
        // TODO add your handling code here:
        lblChung.setText("Số lỗi phát hiện");
        txtChung.setVisible(true);
    }//GEN-LAST:event_rbtKiemChungVienActionPerformed

    private void tblHienThiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHienThiMouseClicked
        // TODO add your handling code here:
        int clickedRow = tblHienThi.getSelectedRow();
    if (clickedRow >= 0) {
        ArrayList<NhanVien> employees = a.getA();
        NhanVien y = employees.get(clickedRow);

        txtMa.setText(y.getMaNhanVien());
        txtHoTen.setText(y.getHoTen());
        txtSDT.setText(y.getSoDienThoai());
        txtEmail.setText(y.getMail());
        txtNgaySinh.setText(String.valueOf(y.getNgaySinh()));
        if (y.isGioiTinh()) {
            rbtNam.setSelected(true);
        } else {
            rbtNu.setSelected(true);
        }
        txtLuongCoBan.setText(String.valueOf(y.getLuongCoBan()));

        if (y instanceof LapTrinhVien) {
            rbtLapTrinhVien.setSelected(true);
            lblChung.setText("Số giờ tăng ca");
            txtChung.setText(String.valueOf(((LapTrinhVien) y).getSoGioTangCa()));
            txtChung.setVisible(true);
        } else if (y instanceof KiemChungVien) {
            rbtKiemChungVien.setSelected(true);
            lblChung.setText("Số lỗi phát hiện");
            txtChung.setText(String.valueOf(((KiemChungVien) y).getSoLoiPhatHien()));
            txtChung.setVisible(true);
        }
    }
    }//GEN-LAST:event_tblHienThiMouseClicked

    private void btnCapNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCapNhatActionPerformed
        // TODO add your handling code here:
        int chon =  JOptionPane.showConfirmDialog(null, "Bạn muốn lưu thông tin");
        if(chon == 0){
            int index = tblHienThi.getSelectedRow();
            String ma = txtMa.getText();
            String ten = txtHoTen.getText();
            String sdt = txtSDT.getText();
            String mail = txtEmail.getText();
            Date nt = new Date(txtNgaySinh.getText());
            boolean gioiTinh = rbtNam.isSelected();
            double luongCoBan = Double.parseDouble(txtLuongCoBan.getText());
            NhanVien x = null;

            if (rbtLapTrinhVien.isSelected()) {
                int soGioTangCa = Integer.parseInt(txtChung.getText());
                x = new LapTrinhVien(soGioTangCa, ma, ten, sdt, mail, nt, gioiTinh, luongCoBan);
            } else if (rbtKiemChungVien.isSelected()) {
                int soLoiPhatHien = Integer.parseInt(txtChung.getText());
                x = new KiemChungVien(soLoiPhatHien, ma, ten, sdt, mail, nt, gioiTinh, luongCoBan);
            }
            ArrayList<NhanVien> b = a.getA();
            b.set(index, x);
            a.setA(b);
            JOptionPane.showMessageDialog(null, "Chỉnh sửa thành công!");
            loadData(b);
            lblHienThi.setText("Bạn vừa cập nhận thông tin mã: "+ma);
            
        }
    }//GEN-LAST:event_btnCapNhatActionPerformed

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        int xoa = tblHienThi.getSelectedRow();

        if (xoa == -1) {
            JOptionPane.showMessageDialog(null, "Hãy chọn 1 đối tượng cần xóa");
        } else {
            int luachon = JOptionPane.showConfirmDialog(null, "Bạn muốn xóa?");
            if (luachon == JOptionPane.YES_OPTION) {
                // Xóa hàng được chọn từ DefaultTableModel (được gán cho dtm)
                DefaultTableModel model = (DefaultTableModel) tblHienThi.getModel();
                model.removeRow(xoa); // Xóa hàng tại chỉ mục xoa

                JOptionPane.showMessageDialog(null, "Đã xóa thành công");

                // Cập nhật dữ liệu trong ArrayList hoặc danh sách khác nếu cần
                // Ví dụ: a là đối tượng chứa danh sách NhanVien
                ArrayList<NhanVien> x = a.getA();
                if (xoa < x.size()) {
                    x.remove(xoa);
                    a.setA(x); // Cập nhật danh sách sau khi xóa
                }

                ClearForm();
            }
        }
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        ClearForm();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnThongKeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongKeActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(null,"Số Nhân Viên Lập Trình: "+a.thongKe("LapTrinhVien")
                +"\nSố Nhân Viên Kiểm Chứng: "+a.thongKe("KiemChungVien")+
                "\nTổng lương Nhân Viên CTY: "+a.tongLuong());
    }//GEN-LAST:event_btnThongKeActionPerformed

    private void btnLuuFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuFileActionPerformed
        // TODO add your handling code here:
        String tenfile = JOptionPane.showInputDialog(null, "Tên file:");
        int luachon = JOptionPane.showConfirmDialog(null, "Bạn muốn lưu File");
        if (luachon == JOptionPane.YES_OPTION) {
            
            a.ghiFile(tenfile+".txt");
            loadData(a.getA());
            JOptionPane.showMessageDialog(null, "Lưu File thành Công!");
            lblHienThi.setText("Bạn vừa lưu file:"+tenfile+".txt");
        }      

    }//GEN-LAST:event_btnLuuFileActionPerformed

    private void btnLuongCaoNhatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuongCaoNhatActionPerformed
        // TODO add your handling code here:
        ArrayList<NhanVien> Max = a.LuongNVCaoNhat();
        JOptionPane.showMessageDialog(null, "Trên bảng là NV có lương cao nhất");
        loadData(Max);    
    }//GEN-LAST:event_btnLuongCaoNhatActionPerformed

    private void cxbTachActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxbTachActionPerformed
        // TODO add your handling code here:
        String selectedType = cxbTach.getSelectedItem().toString();
        if (selectedType.equals("ALL")) {
            loadData(a.getA());
        }
        if (selectedType.equals("Lập trình viên")) {
            ArrayList<NhanVien> lapTrinhViens = a.tachNhanVien("LapTrinhVien");
            if (!lapTrinhViens.isEmpty()) {
                loadData(lapTrinhViens);
            } else {
                JOptionPane.showMessageDialog(null, "Không có nhân viên Lập trình viên trong danh sách");
            }
        } else if (selectedType.equals("Kiểm chứng viên")) {
            ArrayList<NhanVien> kiemChungViens = a.tachNhanVien("KiemChungVien");
            if (!kiemChungViens.isEmpty()) {
                loadData(kiemChungViens);
            } else {
                JOptionPane.showMessageDialog(null, "Không có nhân viên Kiểm chứng viên trong danh sách");
            }
        }
    }//GEN-LAST:event_cxbTachActionPerformed

    private void rbtNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtNamActionPerformed

    private void btnXoaMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaMaActionPerformed
        // TODO add your handling code here:
        String maxoa = JOptionPane.showInputDialog(null, "Nhập mã nhân viên cần xóa");
        boolean  xoa = a.xoaNhanVienTheoMa(maxoa);
        if(xoa){
            int luachon = JOptionPane.showConfirmDialog(null, "Bạn có muốn xóa mã"+maxoa);
            if(luachon == JOptionPane.YES_OPTION){
                JOptionPane.showMessageDialog(null, "Đã xóa nhân viên "+maxoa+" thành công");
                loadData(a.getA());
            }else JOptionPane.showMessageDialog(null, "Chưa thực hiện");

        }else JOptionPane.showMessageDialog(null, "Không có mã "+maxoa);
        
    }//GEN-LAST:event_btnXoaMaActionPerformed

    private void btnTimTheoMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTimTheoMaActionPerformed
        // TODO add your handling code here:
        String t = JOptionPane.showInputDialog(null, "Nhập mã Nhân viên cần tìm");
        ArrayList<NhanVien> tim = a.timNVTheoMa(t);
        int timkiem = JOptionPane.showConfirmDialog(null, "Bạn có muốn tìm"+t);
        if(timkiem==JOptionPane.YES_OPTION){
            
            loadData(tim);
        }
        
    }//GEN-LAST:event_btnTimTheoMaActionPerformed

    private void cxbSapXepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cxbSapXepActionPerformed
        // TODO add your handling code here:
        String selectedType = cxbSapXep.getSelectedItem().toString();
        if (selectedType.equals("Sắp Xếp Lương Tăng")) {
            a.sapXepTangLuong();
            loadData(a.getA());
        } else if (selectedType.equals("Sắp Xếp Lương Giảm")) {
            a.sapXepGiamLuong();
            loadData(a.getA());
        }
    }//GEN-LAST:event_cxbSapXepActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnThoatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCapNhat;
    private javax.swing.JButton btnDocFile;
    private javax.swing.JButton btnLuongCaoNhat;
    private javax.swing.JButton btnLuuFile;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThongKe;
    private javax.swing.JButton btnTimTheoMa;
    private javax.swing.JButton btnXoa;
    private javax.swing.JButton btnXoaMa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox<String> cxbSapXep;
    private javax.swing.JComboBox<String> cxbTach;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblChung;
    private javax.swing.JLabel lblGT;
    private javax.swing.JLabel lblHienThi;
    private javax.swing.JLabel lblHoTen;
    private javax.swing.JLabel lblMa;
    private javax.swing.JLabel lblMail;
    private javax.swing.JLabel lblMail3;
    private javax.swing.JLabel lblNgaySinh;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblSDT;
    private javax.swing.JLabel lblTach;
    private javax.swing.JLabel lblTach1;
    private javax.swing.JRadioButton rbtKiemChungVien;
    private javax.swing.JRadioButton rbtLapTrinhVien;
    private javax.swing.JRadioButton rbtNam;
    private javax.swing.JRadioButton rbtNu;
    private javax.swing.JTable tblHienThi;
    private javax.swing.JTextField txtChung;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLuongCoBan;
    private javax.swing.JTextField txtMa;
    private javax.swing.JTextField txtNgaySinh;
    private javax.swing.JTextField txtSDT;
    // End of variables declaration//GEN-END:variables
    public void loadData(ArrayList<NhanVien> b){
         while (dtm.getRowCount() > 0) {
            dtm.removeRow(0);
        }
        for (NhanVien x : b) {
            if (x instanceof LapTrinhVien) {
                dtm.addRow(new Object[]{"Lập trình",x.getMaNhanVien(),x.getHoTen(),x.getSoDienThoai(),x.getMail(),x.getNgaySinh(),(x.isGioiTinh()==true?"Nam":"Nữ"),x.getLuongCoBan(),((LapTrinhVien) x).getSoGioTangCa(),"",x.getLuong()});
            }
            if (x instanceof KiemChungVien) {
                dtm.addRow(new Object[]{"Kiểm chứng",x.getMaNhanVien(),x.getHoTen(),x.getSoDienThoai(),x.getMail(),x.getNgaySinh(),(x.isGioiTinh()==true?"Nam":"Nữ"),x.getLuongCoBan(),"",((KiemChungVien) x).getSoLoiPhatHien(),x.getLuong()});
            }
        }
    }
    private void ClearForm() {
        //Xóa trống
        txtMa.setText("");
        txtHoTen.setText("");
        txtSDT.setText("");
        txtEmail.setText("");
        txtNgaySinh.setText(String.valueOf(""));
        rbtNam.setSelected(true);
        rbtNu.setSelected(false);
        txtLuongCoBan.setText(String.valueOf(""));
        txtChung.setText("");
        
        //Xóa màu nếu có
        txtMa.setBackground(Color.white);
        txtHoTen.setBackground(Color.white);
        txtSDT.setBackground(Color.white);
        txtEmail.setBackground(Color.white);
        txtNgaySinh.setBackground(Color.white);
        txtLuongCoBan.setBackground(Color.white);
        txtChung.setBackground(Color.white);
        
        
    }
    
}
